import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createWorkspaceBrief, formatWorkspaceBrief } from "../packages/tutor-kit/dist/cli/brief.js";
import { recordDoctorEvidence } from "../packages/tutor-kit/dist/cli/evidence.js";
import { formatProgress, summarizeProgress } from "../packages/tutor-kit/dist/cli/progress.js";
import { addTextbook, initWorkspace } from "../packages/tutor-kit/dist/cli/workspace.js";
import { compileWorkspace } from "../packages/tutor-kit/dist/compile/compile.js";
import { clearWorkspaceCaches } from "../packages/tutor-kit/dist/compile/discover.js";
import { verifyCodingProblems } from "../packages/tutor-kit/dist/compile/verify-coding.js";
import { linkTutorKit } from "./helpers/tutor-kit.ts";

test.afterEach(() => {
  clearWorkspaceCaches();
});

test("progress compacts quiz, coding, glossary, and highlight events", async () => {
  const dir = mkdtempSync(join(tmpdir(), "tutor-kit-"));
  initWorkspace(dir, { starter: true });
  linkTutorKit(dir);
  const events = [
    {
      type: "quiz_checked",
      textbookId: "getting-started",
      chapterId: "welcome",
      quizId: "authoring-review",
      score: 3,
      total: 4,
      responses: [
        { questionId: "source-file-location", selectedAnswer: "b", correct: false },
        { questionId: "compile-purpose", selectedAnswer: "c", correct: true }
      ],
      createdAt: "2026-07-14T10:00:00.000Z"
    },
    {
      type: "coding_action_ran",
      textbookId: "getting-started",
      chapterId: "welcome",
      blockId: "classify-workspace-paths",
      exitCode: 1,
      timedOut: false,
      createdAt: "2026-07-14T10:01:00.000Z"
    },
    {
      type: "glossary_card_rated",
      textbookId: "getting-started",
      termId: "semantic-block",
      rating: "again",
      createdAt: "2026-07-14T10:02:00.000Z"
    },
    {
      type: "highlight_created",
      textbookId: "getting-started",
      chapterId: "welcome",
      highlightId: "h1",
      status: "open",
      createdAt: "2026-07-14T10:03:00.000Z"
    }
  ];
  writeFileSync(join(dir, "tutor-data", "events.jsonl"), `${events.map((event) => JSON.stringify(event)).join("\n")}\nnot-json\n`);

  const progress = await summarizeProgress(dir, { textbookId: "getting-started" });
  assert.equal(progress.eventCount, 4);
  assert.equal(progress.invalidEventCount, 1);
  assert.equal(progress.quizzes[0]?.latestScore, 3);
  assert.deepEqual(progress.quizzes[0]?.missedQuestionIds, ["source-file-location"]);
  assert.deepEqual(progress.weakTags, [{ tag: "curriculum-source", misses: 1 }, { tag: "tutor-kit", misses: 1 }]);
  assert.equal(progress.coding[0]?.passed, false);
  assert.deepEqual(progress.glossaryAgain, [{ termId: "semantic-block", count: 1 }]);
  assert.equal(progress.openHighlights, 1);
  assert.match(formatProgress(progress), /weak tags: curriculum-source \(1\), tutor-kit \(1\)/);
});

test("brief reports compact source, chapter, authoring, and progress state", async () => {
  const dir = mkdtempSync(join(tmpdir(), "tutor-kit-"));
  initWorkspace(dir, { starter: true });
  linkTutorKit(dir);
  addTextbook(dir, "sql", "SQL Foundations");

  const brief = await createWorkspaceBrief(dir);
  const sql = brief.textbooks.find((textbook) => textbook.id === "sql");
  assert.deepEqual(sql?.authoringFiles, ["textbooks/sql/course.md"]);
  assert.equal(brief.textbooks.find((textbook) => textbook.id === "getting-started")?.chapters.length, 1);
  assert.match(formatWorkspaceBrief(brief), /textbook sql: SQL Foundations/);
  assert.match(formatWorkspaceBrief(brief), /suggested next move:/);
});

test("doctor evidence is written by Tutor Kit", async () => {
  const dir = mkdtempSync(join(tmpdir(), "tutor-kit-"));
  initWorkspace(dir, { starter: true });
  linkTutorKit(dir);

  const compile = await compileWorkspace(dir, { textbookId: "getting-started" });
  const verification = await verifyCodingProblems(dir, { textbookId: "getting-started" });
  const path = await recordDoctorEvidence(dir, "getting-started", compile, verification);

  assert.equal(existsSync(path), true);
  const evidence = readFileSync(path, "utf8");
  assert.match(evidence, /Generated by Tutor Kit/);
  assert.match(evidence, /Result: Passed/);
  assert.match(evidence, /starter failed as expected; reference solution passed/);
});
